version: '2'
services:
  my_chef:
    container_name: my_chef
    hostname: my_chef
    # https://hub.docker.com/r/chef/chefdk/
    image: chef/chefdk
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ./config:/tmp/config
      - ./cookbooks:/tmp/cookbooks
      - ./test.sh:/tmp/test.sh
