version: '2'
services:
  chef_server:
    container_name: chef_server
    hostname: chef_server
    # https://hub.docker.com/r/base/chef-server/~/dockerfile/
    image: base/chef-server
    # entrypoint: ["tail", "-f", "/dev/null"]
    privileged: true
    ports:
    - "443:443"
  chef_knife:
    container_name: chef_knife
    hostname: chef_knife
    # https://hub.docker.com/r/chef/chefdk/
    image: chef/chefdk
    entrypoint: ["tail", "-f", "/dev/null"]
  chef_client:
    container_name: chef_client
    hostname: chef_client
    # https://hub.docker.com/r/chef/chefdk/
    image: chef/chefdk
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ./config:/tmp/config
      - ./cookbooks:/tmp/cookbooks
