---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.17.44
  data_path: test/shared
  client_rb:
      file_cache_path: "/var/chef/cache"

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[example::default]
    attributes:
        {example:
                {update_version: '1.1'
                }
        }

